language: php

php:
- 7.0
- 7.1
- 7.2

install:
- pecl install -f -y swoole-4.2.8
before_script:
- composer update --dev

script: composer test

cache:
  directories:
  - "$HOME/.composer/cache/files"