language: php

php:
- 7.0
- 7.1
- 7.2

install:
- git clone https://github.com/swoole/swoole-src.git && cd swoole-src && phpize && ./configure && sudo make -j$(nproc) && sudo make install && sudo ldconfig && cd ..
before_script:
- composer update --dev
- chmod a+x ./bin/server

script: ./bin/server start

cache:
  directories:
  - "$HOME/.composer/cache/files"